from datetime import datetime
birthday = datetime(1973,2,4)
birthday.strftime("%Y-%m-%d")
birthday.strftime('%b %d, %Y')
birthday.strftime('%d %B %Y')
birthday.strftime('%Y/%m/%d')
birthday.strftime('%m/%d/%Y')
birthday.strftime('%A/%Y/%m/%d')
birthday.strftime('%b %d, %Y')
birthday.strftime('%d %B %Y')
birthday.strftime('%Y/%m/%d')
birthday.strftime('%m/%d/%Y')
birthday.strftime('%A/%Y/%m/%d')
